services:
  pairqr:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: pairqr-app
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - HMAC_SECRET=${HMAC_SECRET}
      - SESSION_TTL_MINUTES=${SESSION_TTL_MINUTES:-2}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173,http://localhost:3000}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_TTL_SECONDS=${REDIS_TTL_SECONDS:-300}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/pairqr}
      - TURN_STATIC_SECRET=${TURN_STATIC_SECRET}
      - TURN_REALM=${TURN_REALM:-pairqr}
      - TURN_URIS=${TURN_URIS:-turn:coturn:3478?transport=udp,turn:coturn:3478?transport=tcp}
    ports:
      - "3000:80"
    depends_on:
      - redis
      - postgres
      - coturn

  coturn:
    image: instrumentisto/coturn
    container_name: pairqr-coturn
    restart: unless-stopped
    command: >
      --no-cli --no-tcp-relay
      --listening-port=3478
      --realm=${TURN_REALM:-pairqr}
      --use-auth-secret
      --static-auth-secret=${TURN_STATIC_SECRET}
      --min-port=49152
      --max-port=49200
      --no-stdout-log
    ports:
      - "3478:3478/udp"
      - "3478:3478"

  redis:
    image: redis:7-alpine
    container_name: pairqr-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    container_name: pairqr-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pairqr
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
