name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - 'shared/**'
      - 'scripts/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Droplet (production)
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      SSH_HOST: ${{ secrets.DO_HOST }}
      SSH_USER: ${{ secrets.DO_SSH_USER }}
      SSH_KEY:  ${{ secrets.DO_SSH_KEY }}
      SSH_PORT: ${{ secrets.DO_SSH_PORT || '22' }}
      PROJECT_DIR: ${{ secrets.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate required secrets (minimal for copy step)
        run: |
          set -euo pipefail
          missing=0
          for k in SSH_HOST SSH_USER SSH_KEY PROJECT_DIR; do
            if [ -z "${!k:-}" ]; then echo "❌ Missing secret: $k"; missing=1; else echo "✅ Found: $k"; fi
          done
          if [ "$missing" -eq 1 ]; then
            echo "Add missing secrets in Settings » Secrets and variables » Actions." >&2
            exit 1
          fi

      - name: Inspect files to upload
        run: |
          set -euxo pipefail
          shopt -s globstar nullglob dotglob
          files=( ./server/** ./shared/** ./scripts/** )
          printf 'Matched files:\n'; printf ' - %s\n' "${files[@]}"
          (( ${#files[@]} )) || { echo "No files matched. Check paths or add files."; exit 1; }

      - name: Copy server files to Droplet
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          source: "./server/**,./shared/**,./scripts/**"
          target: ${{ env.PROJECT_DIR }}/
          overwrite: true
          strip_components: 0
          timeout: 30s
          command_timeout: 10m

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script_stop: true
          script: |
            set -euo pipefail
            PROJECT_DIR="${PROJECT_DIR}"

            if ! command -v curl >/dev/null 2>&1; then
              sudo apt-get update -y && sudo apt-get install -y curl
            fi
            if ! command -v ufw >/dev/null 2>&1; then
              sudo apt-get update -y && sudo apt-get install -y ufw || true
            fi

            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sh
            fi
            sudo systemctl enable --now docker || true

            if command -v ufw >/dev/null 2>&1; then
              sudo ufw allow 3000/tcp || true
              sudo ufw allow 3478/tcp || true
              sudo ufw allow 3478/udp || true
            fi

            mkdir -p "$PROJECT_DIR/server"
            cd "$PROJECT_DIR"

            cat > server/.env << 'EOF'
            NODE_ENV=production
            PORT=3000
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            HMAC_SECRET=${{ secrets.HMAC_SECRET }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
            RATE_LIMIT_WINDOW_MS=60000
            RATE_LIMIT_MAX=100
            REDIS_TTL_SECONDS=300
            TURN_STATIC_SECRET=${{ secrets.TURN_STATIC_SECRET }}
            TURN_REALM=pairqr
            EOF

            COMPOSE="docker compose"
            if ! docker compose version >/dev/null 2>&1; then COMPOSE="docker-compose"; fi

            sudo $COMPOSE --env-file server/.env -f server/docker-compose.yml up -d --build

            set +e
            for i in $(seq 1 20); do
              status=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3000/health || true)
              if [ "$status" = "200" ]; then echo "✅ Service healthy (HTTP 200)."; ok=1; break; fi
              echo "⏳ Waiting for service... ($i/20) Last status: ${status:-N/A}"
              sleep 3
            done
            set -e
            if [ "${ok:-0}" -ne 1 ]; then
              echo "⚠️ Health check failed. Recent logs:"
              sudo $COMPOSE -f server/docker-compose.yml ps
              sudo $COMPOSE -f server/docker-compose.yml logs --tail=200 || true
              exit 1
            fi

            sudo docker system prune -af --filter "until=24h" || true
